### ISSUE TITLE
Docs do not contain information about sft.conf. 

### ISSUE THREAD

**Issue by lakshmi-kannan** [ScaleFT/docs#46]
While debugging sft resolve, I bumped into message https://gist.github.com/lakshmi-kannan/02d6525eb31dab8bce68c53c9a548e1f#file-gistfile1-txt-L3 and tried to look up docs to get a sft.conf created on my box. I couldn't find the schema for the config. A sample config shipped with the client packages will also help.

**Comment by lakshmi-kannan** [comment]
```

**Comment by pquerna** [comment]
The primary interface for this is through the `sft config` command line, which has been improved quite a bit since 1.15
